project:
  type: book
  pre-render: utils/boa-config.ts
  post-render: mv tmp/_quarto-boa.yaml _quarto-boa.yaml
book:
  title: TEI2026
  chapters:
    - index.qmd
    - contributions/*.qmd
format:
  pdf:
    documentclass: scrbook
    classoption:
      - twocolumn
