project:
  type: book
book:
  title: TEI2026
  chapters:
    - index.qmd
    - ./contributions/.DS_Store
    - ./contributions/001.qmd
    - ./contributions/001_files
format:
  pdf:
    documentclass: scrbook
    classoption:
      - twocolumn
